name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Otomatis jalan setiap 12 jam
  workflow_dispatch: # Memungkinkan kamu menjalankan manual dari tab Actions
  push:
    branches:
    - main # Jalan setiap kamu push ke main

jobs:
  generate:
    permissions: 
      contents: write # WAJIB: Agar action bisa menulis file ke repositori
    runs-on: ubuntu-latest
    steps:
      # LANGKAH PENTING: Mengambil isi repo ke runner
      - name: Checkout
        uses: actions/checkout@v4

      # Membuat ular berdasarkan kontribusi
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Mizzuue
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Mengunggah hasil ke branch 'output'
      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
